### ISSUE TITLE
ASaaS Todos

### ISSUE THREAD

**Issue by whatl3y** [moontography/moontography#66]
- [ ] Have buttons for swap creators to deposit/withdraw tokens and deactivate swaps
- [x] Better network switching behavior handling
- [ ] List of all user's swaps (at least most recent)
- [x] Error handling 
- [x] Prevent initiating a new swap if the target bridge does not have enough liquidity to fulfill the swap

**Comment by calsupik** [comment]
Small mobile UI overflow issue:

![image](https://user-images.githubusercontent.com/2244987/126499412-4271b5db-b1b7-4bae-8070-b936b9c8a7f3.png)
