### ISSUE TITLE
Website not loading FaaS page

### ISSUE THREAD

**Issue by cl-tim** [moontography/moontography#92]
Hi guys,

The FaaS page isn't loading farms at the moment, just throwing this error message on opening.

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/74086338/186042415-bedfc62a-a060-4b98-8d37-edfbde237ca6.png">

No errors are thrown in the browser console.

**Comment by whatl3y** [comment]
Thanks @cl-tim! We were doing some maintenance causing this but it is now resolved. Please hard refresh and confirm they are loading for you as expected. Thanks again!

**Comment by cl-tim** [comment]
All good now, cheers!
